/**
 * NetPulse REST API catalog for /api-docs explorer.
 * pageKey: omit = any authenticated user; set = requires that portal page.
 */

/** @typedef {{ name: string, placeholder?: string, description?: string, example?: string }} ApiDocParam */

/** @param {Record<string, unknown>} o */
function ep(o) {
  return {
    auth: true,
    sampleBody: null,
    pathParams: [],
    queryParams: [],
    responseExample: null,
    notes: [],
    ...o,
  }
}

export const API_DOC_GROUPS = [
  { id: 'intro', label: 'Getting started', intro: true },
  { id: 'auth', label: 'Authentication & tokens' },
  { id: 'agent', label: 'External agent API' },
  { id: 'ai', label: 'SocMon AI', pageKey: 'ai' },
  { id: 'store', label: 'Store monitor (live)', pageKey: 'storeMonitor' },
  { id: 'store-alerts', label: 'Store alerts', pageKey: 'storeMonitor' },
  { id: 'soc', label: 'SOC — firewall & logs', pageKey: 'soc' },
  { id: 'noc', label: 'NOC — network stats', pageKey: 'noc' },
  { id: 'sentinel', label: 'Sentinel (Elasticsearch)', pageKey: 'sentinel' },
  { id: 'sentinel-one', label: 'SentinelOne console & XDR', pageKey: 'sentinel' },
  { id: 'zabbix', label: 'Infra Zabbix', pageKey: 'infra' },
  { id: 'store-zabbix', label: 'Store Zabbix', pageKey: 'storeZabbix' },
  { id: 'admin', label: 'Admin — users & devices', pageKey: 'admin' },
  { id: 'system', label: 'System' },
]

export const API_DOC_ENDPOINTS = [
  ep({
    id: 'health',
    groupId: 'system',
    method: 'GET',
    path: '/health',
    title: 'Health check',
    auth: false,
    description:
      'Liveness probe. No authentication. Use before calling authenticated routes.',
    responseExample: { status: 'ok', version: '1.0.0', ai: 'ollama' },
  }),

  // ── Auth ──────────────────────────────────────────────────────────────────
  ep({
    id: 'auth-login',
    groupId: 'auth',
    method: 'POST',
    path: '/api/auth/login',
    title: 'Login (portal session)',
    auth: false,
    description:
      'Returns a short-lived session JWT (typ: session) and user profile with allowedPages / pageAccess. Use this for browser login — not for long-lived automation.',
    sampleBody: { email: 'user@example.com', password: 'your-password' },
    responseExample: {
      token: 'eyJhbGciOiJIUzI1NiIs…',
      user: { id: '…', email: 'user@example.com', role: 'analyst', allowedPages: ['soc', 'storeMonitor'] },
    },
    notes: ['Session tokens cannot create or revoke API tokens.'],
  }),
  ep({
    id: 'auth-me',
    groupId: 'auth',
    method: 'GET',
    path: '/api/auth/me',
    title: 'Current user profile',
    description:
      'Returns id, name, email, role, allowedPages, pageAccess, customRoleId, apiAccessEnabled, theme. Works with session JWT or API JWT.',
    responseExample: {
      id: '…',
      email: 'user@example.com',
      role: 'analyst',
      allowedPages: ['soc', 'storeMonitor', 'ai'],
      pageAccess: { soc: 'full', storeMonitor: 'full', ai: 'read' },
      apiAccessEnabled: true,
    },
  }),
  ep({
    id: 'tokens-list',
    groupId: 'auth',
    method: 'GET',
    path: '/api/auth/api-tokens',
    title: 'List API tokens',
    sessionOnly: true,
    description: 'Lists active API tokens (id, label, expiresAt, lastUsedAt). Does not return JWT secrets.',
    responseExample: {
      apiAccessEnabled: true,
      tokens: [{ id: '…', label: 'n8n', expiresAt: '2026-09-01T00:00:00.000Z', lastUsedAt: null }],
    },
  }),
  ep({
    id: 'tokens-create',
    groupId: 'auth',
    method: 'POST',
    path: '/api/auth/api-tokens',
    title: 'Create API JWT',
    sessionOnly: true,
    description:
      'Creates a revocable long-lived JWT (typ: api). Requires apiAccessEnabled on your user (Admin → Users). Max 10 active tokens per user.',
    sampleBody: { label: 'automation-script', expiresIn: '90d' },
    responseExample: {
      token: 'eyJhbGciOiJIUzI1NiIs…',
      id: '…',
      label: 'automation-script',
      expiresAt: '2026-09-01T00:00:00.000Z',
      message: 'Copy this token now. It will not be shown again.',
    },
    notes: ['expiresIn: 30d | 90d | 180d | 365d (or env JWT_API_EXPIRES_IN default).'],
  }),
  ep({
    id: 'tokens-revoke',
    groupId: 'auth',
    method: 'DELETE',
    path: '/api/auth/api-tokens/{tokenId}',
    title: 'Revoke API token',
    sessionOnly: true,
    description: 'Immediately invalidates the token. Scripts using it will receive 401.',
    pathParams: [{ name: 'tokenId', placeholder: 'mongo-object-id', description: 'From GET /api/auth/api-tokens' }],
    responseExample: { ok: true },
  }),

  // ── Agent ─────────────────────────────────────────────────────────────────
  ep({
    id: 'agent-meta',
    groupId: 'agent',
    method: 'GET',
    path: '/api/agent/meta',
    title: 'Agent API metadata',
    description:
      'Version, authMethod (jwt | agent_key | api_jwt), service user, allowedPages, configured forward URLs, endpoint map.',
    responseExample: {
      version: '1',
      authMethod: 'jwt',
      allowedPages: ['storeMonitor', 'soc', 'sentinel'],
      endpoints: { query: 'POST /api/agent/query', context: 'POST /api/agent/context' },
    },
    notes: ['Also accepts X-Netpulse-Agent-Key when NETPULSE_AGENT_API_KEY is set on server.'],
  }),
  ep({
    id: 'agent-modules',
    groupId: 'agent',
    method: 'GET',
    path: '/api/agent/modules',
    title: 'Context modules',
    description: 'Module ids you may pass to /context or /query: storeMonitor, storeProblems, soc, etc.',
    responseExample: {
      modules: [{ id: 'storeMonitor', label: 'Store Monitor', freshness: 'live' }],
    },
  }),
  ep({
    id: 'agent-context',
    groupId: 'agent',
    method: 'POST',
    path: '/api/agent/context',
    title: 'Export portal context (no LLM)',
    description:
      'Fetches live/periodic portal JSON for external agents. format: json | prompt | both — includes a text block suitable for LLM system context.',
    sampleBody: {
      question: 'store monitor summary',
      modules: ['storeMonitor', 'storeProblems'],
      autoModules: true,
      format: 'both',
    },
    responseExample: {
      portalContext: { portal: 'netpulse', modules: {} },
      contextPreview: { storeMonitor: { total: 1200, offline: 5 } },
      modulesUsed: ['storeMonitor'],
      prompt: '=== NETPULSE PORTAL CONTEXT ===',
    },
    notes: [
      'modules: optional string[] — omit with autoModules:true to pick from question keywords.',
      'Does not call Claude/OpenAI/Ollama.',
    ],
  }),
  ep({
    id: 'agent-query',
    groupId: 'agent',
    method: 'POST',
    path: '/api/agent/query',
    title: 'Query + direct answers',
    description:
      'Best endpoint for automation. Runs fast paths (stores, XDR, Zabbix, SOC, hostname) when the question matches; returns directAnswer.content when available.',
    sampleBody: {
      question: 'How many stores are offline?',
      includeContext: true,
      autoModules: true,
    },
    responseExample: {
      source: 'netpulse',
      question: 'How many stores are offline?',
      directAnswer: { content: 'Store Monitor (LIVE)…', mode: 'direct-store', fastPath: true },
      portalContext: {},
      modulesUsed: ['storeMonitor', 'storeProblems'],
    },
  }),
  ep({
    id: 'agent-forward',
    groupId: 'agent',
    method: 'POST',
    path: '/api/agent/forward',
    title: 'Forward custom payload',
    description: 'POST your own JSON to downstream webhook URL(s). Optional NETPULSE_AGENT_FORWARD_SECRET header on target.',
    sampleBody: {
      url: 'https://your-agent.example/hooks/netpulse',
      payload: { custom: 'data' },
    },
    responseExample: { ok: true, delivered: [{ url: 'https://…', ok: true, status: 200 }] },
  }),
  ep({
    id: 'agent-deliver',
    groupId: 'agent',
    method: 'POST',
    path: '/api/agent/deliver',
    title: 'Query + forward (one call)',
    description: 'Runs /query then POSTs the full envelope to url or env NETPULSE_AGENT_FORWARD_URL(S).',
    sampleBody: {
      question: 'Sentinel failed login last 1 hour',
      url: 'https://your-agent.example/hooks/netpulse',
      includeContext: true,
    },
  }),

  // ── AI ────────────────────────────────────────────────────────────────────
  ep({
    id: 'ai-modules',
    groupId: 'ai',
    pageKey: 'ai',
    method: 'GET',
    path: '/api/ai/modules',
    title: 'AI context modules',
    description: 'Same module list as agent API, filtered by your allowedPages.',
    responseExample: { modules: [{ id: 'storeMonitor', label: 'Store Monitor', freshness: 'live' }] },
  }),
  ep({
    id: 'ai-provider',
    groupId: 'ai',
    pageKey: 'ai',
    method: 'GET',
    path: '/api/ai/provider',
    title: 'AI provider status',
    description: 'Active LLM (claude | openai | ollama), model name, configuration rows, hints.',
    responseExample: {
      provider: 'ollama',
      model: 'llama3.1:8b',
      active: 'ollama',
      rows: [{ key: 'ollama', label: 'Ollama (OLLAMA_HOST)', value: 'http://192.168.1.50:11434', ok: true }],
    },
  }),
  ep({
    id: 'ai-chat',
    groupId: 'ai',
    pageKey: 'ai',
    method: 'POST',
    path: '/api/ai/chat',
    title: 'AI chat (multi-turn)',
    description:
      'Primary AI endpoint. mode: monitor | details | rca. Fast paths return fastPath:true without calling LLM. Timeout up to ~6 min.',
    sampleBody: {
      messages: [
        { role: 'user', content: 'How many stores are offline?' },
      ],
      modules: ['storeMonitor', 'storeProblems'],
      autoModules: true,
      mode: 'monitor',
    },
    responseExample: {
      content: 'Store Monitor (LIVE)…',
      fastPath: true,
      modulesUsed: ['storeMonitor'],
      metrics: { mode: 'direct', totalMs: 420, llmMs: 0 },
    },
    notes: [
      'details mode — full hostname bundle (Store Monitor + Sentinel + SOC + NOC).',
      'rca mode — correlated root-cause analysis.',
    ],
  }),
  ep({
    id: 'ai-search',
    groupId: 'ai',
    pageKey: 'ai',
    method: 'POST',
    path: '/api/ai/search',
    title: 'Natural language log search',
    description: 'Converts a question to Elasticsearch DSL and runs it on firewall-* / cisco-* indices.',
    sampleBody: { question: 'failed login from 10.0.0.5 in last 24 hours' },
    responseExample: { total: 42, hits: [{ '@timestamp': '…', 'srcip': '10.0.0.5' }] },
  }),
  ep({
    id: 'ai-triage',
    groupId: 'ai',
    pageKey: 'ai',
    method: 'POST',
    path: '/api/ai/triage',
    title: 'Alert triage',
    description: 'LLM triage for a single alert object (severity, summary, recommended actions).',
    sampleBody: {
      alert: { title: 'Store offline', severity: 'high', hostname: 'RP4531-E521BCXS' },
    },
  }),
  ep({
    id: 'ai-anomalies',
    groupId: 'ai',
    pageKey: 'ai',
    method: 'GET',
    path: '/api/ai/anomalies',
    title: 'Anomaly detection',
    description: 'LLM summary of anomalies in last 1 hour. Optional site filter.',
    queryParams: [
      { name: 'site', placeholder: 'store-tag or hostname', description: 'Optional site filter' },
    ],
  }),

  // ── Store monitor ─────────────────────────────────────────────────────────
  ep({
    id: 'store-full',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/full',
    title: 'Full bundle (all store monitor data)',
    description:
      'Primary wide API — one call returns live summary, every store row, flattened problems, crash aggregates, settings, and store alert rules/events. Use this instead of calling overview + problems + crashes + alerts separately.',
    queryParams: [
      { name: 'staleMinutes', placeholder: '10', description: 'Stale threshold minutes (2–60)', example: '10' },
      { name: 'range', placeholder: '-24h', description: 'Store metrics window', example: '-24h' },
      { name: 'crashRange', placeholder: '-24h', description: 'Crash window (defaults to range)', example: '-24h' },
      { name: 'q', placeholder: 'RP4531', description: 'Filter hostname / storeTag / serial / IP' },
      { name: 'connState', placeholder: 'offline', description: 'online | offline | unknown' },
      { name: 'issuesOnly', placeholder: 'true', description: 'Only stores with issues' },
      { name: 'includeCrashes', placeholder: 'true', description: 'Include crashes block (default true)' },
      { name: 'includeAlerts', placeholder: 'true', description: 'Include alert rules + recent events (default true)' },
      { name: 'includeSettings', placeholder: 'true', description: 'Include monitor settings (default true)' },
      { name: 'includeProblemHistory', placeholder: 'false', description: 'Mongo problem snapshots (heavier)' },
      { name: 'alertEventsLimit', placeholder: '50', description: 'Max recent alert events', example: '50' },
      { name: 'problemHistoryLimit', placeholder: '20', description: 'Max problem history snapshots' },
    ],
    responseExample: {
      summary: { total: 1200, online: 1190, offline: 5, withIssues: 12 },
      stores: [{ hostname: 'RP4531-E521BCXS', storeTag: 'RP4531', connState: 'offline', issues: [] }],
      problems: [],
      crashes: { totalEvents: 42, byApp: [], byType: [] },
      alerts: { rules: [], recentEvents: [] },
      settings: { manualRopSdwanCodeList: [] },
    },
    notes: [
      'Recommended for integrations and dashboards.',
      'For one store time-series use GET /api/store-monitor/stores/{storeTag}/history.',
      'Set includeProblemHistory=true only when you need Mongo snapshot trends.',
    ],
  }),
  ep({
    id: 'store-meta',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/meta',
    title: 'Store monitor meta',
    description: 'Influx URL/bucket status, feature flags, stale defaults.',
    responseExample: { configured: true, bucket: 'stores', org: 'lenskart' },
  }),
  ep({
    id: 'store-overview',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/overview',
    title: 'Overview + all stores (live)',
    description:
      'Primary data API for store health. Returns summary counts plus full store array with connState, metrics, issues.',
    queryParams: [
      { name: 'staleMinutes', placeholder: '10', description: 'Mark stale if no ping (2–60)', example: '10' },
      { name: 'range', placeholder: '-24h', description: 'Metric window: -1h|-3h|-6h|-12h|-24h|-2d|-7d', example: '-24h' },
      { name: 'q', placeholder: 'RP4531', description: 'Search hostname, serial, storeTag, gatewayIp' },
      { name: 'connState', placeholder: 'offline', description: 'Filter: online | offline | unknown' },
      { name: 'issuesOnly', placeholder: 'true', description: '1 | true | yes' },
      { name: 'from', placeholder: '1704067200', description: 'Custom range start (unix sec)' },
      { name: 'to', placeholder: '1704153600', description: 'Custom range end (unix sec)' },
    ],
    responseExample: {
      summary: { total: 1200, online: 1190, offline: 5, withIssues: 12 },
      stores: [{ hostname: 'RP4531-E521BCXS', storeTag: 'RP4531', connState: 'offline', issueCount: 2 }],
      fetchedAt: '2026-06-03T12:00:00.000Z',
    },
  }),
  ep({
    id: 'store-stores',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/stores',
    title: 'Store list (filtered)',
    description: 'Lighter than overview — stores array only with q / connState / issuesOnly filters.',
    queryParams: [
      { name: 'staleMinutes', placeholder: '10', example: '10' },
      { name: 'q', placeholder: 'RP', description: 'Search filter' },
      { name: 'connState', placeholder: 'offline', description: 'online | offline | unknown' },
      { name: 'issuesOnly', placeholder: 'true' },
    ],
    responseExample: { stores: [], total: 0, fetchedAt: '2026-06-03T12:00:00.000Z' },
  }),
  ep({
    id: 'store-history',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/stores/{storeTag}/history',
    title: 'Store metric history',
    description: 'Time series for one store (packet loss, latency, etc.) from Influx.',
    pathParams: [{ name: 'storeTag', placeholder: 'RP4531', description: 'Store tag (URL-encoded if needed)' }],
    queryParams: [
      { name: 'rangeSec', placeholder: '3600', description: 'Fallback window seconds (300–2592000)', example: '86400' },
      { name: 'from', placeholder: '1704067200', description: 'Unix start (sec)' },
      { name: 'to', placeholder: '1704153600', description: 'Unix end (sec)' },
    ],
  }),
  ep({
    id: 'store-problems',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/problems',
    title: 'Active problems (live)',
    description: 'Derived problem list from current store snapshot (not the Mongo periodic snapshot).',
    queryParams: [
      { name: 'staleMinutes', placeholder: '10', example: '10' },
      { name: 'range', placeholder: '-24h', example: '-24h' },
    ],
  }),
  ep({
    id: 'store-problem-history',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/problem-history',
    title: 'Problem history (Mongo)',
    description: 'Periodic snapshot history (~2 min). Use for trends and RCA timelines.',
    queryParams: [
      { name: 'limit', placeholder: '50', description: 'Max snapshots', example: '20' },
      { name: 'hostname', placeholder: 'RP4531-E521BCXS', description: 'Filter one host' },
    ],
  }),
  ep({
    id: 'store-crashes',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/crashes',
    title: 'Application crashes summary',
    description: 'Aggregated crash counts by store/app from Influx event log.',
    queryParams: [
      { name: 'range', placeholder: '-24h', example: '-24h' },
      { name: 'app', placeholder: 'pos', description: 'App name filter' },
      { name: 'hostname', placeholder: 'RP4531-E521BCXS' },
    ],
    responseExample: {
      totalEvents: 120,
      affectedStores: 8,
      affectedStoreList: [{ storeTag: 'RP4531', totalCrashes: 15 }],
    },
  }),
  ep({
    id: 'store-crashes-raw',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/crashes/raw',
    title: 'Crash events (raw)',
    description: 'Individual crash event rows for export or deep dive.',
    queryParams: [
      { name: 'range', placeholder: '-24h', example: '-6h' },
      { name: 'hostname', placeholder: 'RP4531-E521BCXS' },
      { name: 'limit', placeholder: '200', example: '100' },
    ],
  }),
  ep({
    id: 'store-reports',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/reports/{type}',
    title: 'Store reports',
    description: 'type: inventory | uptime | issues | connectivity | speedtest',
    pathParams: [{ name: 'type', placeholder: 'uptime', description: 'inventory|uptime|issues|connectivity|speedtest' }],
    queryParams: [{ name: 'range', placeholder: '-24h', example: '-7d' }],
  }),
  ep({
    id: 'store-settings-get',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/settings',
    title: 'Get monitor settings',
    description: 'Read store monitor thresholds and alert-related settings.',
  }),
  ep({
    id: 'store-settings-put',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'PUT',
    path: '/api/store-monitor/settings',
    title: 'Update monitor settings',
    description: 'Requires full storeMonitor page access (write).',
    sampleBody: { staleMinutes: 10 },
    notes: ['Write access required.'],
  }),

  // ── Store alerts ──────────────────────────────────────────────────────────
  ep({
    id: 'store-alerts-list',
    groupId: 'store-alerts',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-alerts',
    title: 'List alert rules',
    description: 'Influx-based store alert rules (Slack/webhook channels).',
  }),
  ep({
    id: 'store-alerts-events',
    groupId: 'store-alerts',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-alerts/events',
    title: 'Alert events',
    description: 'Fired store alert events with optional filters.',
    queryParams: [
      { name: 'limit', placeholder: '100', example: '50' },
      { name: 'ruleId', placeholder: 'mongo-id' },
    ],
  }),
  ep({
    id: 'store-alerts-status',
    groupId: 'store-alerts',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-alerts/status',
    title: 'Alert engine status',
    description: 'Whether the store alert engine is running and last evaluation time.',
  }),

  // ── SOC / stats / logs ────────────────────────────────────────────────────
  ep({
    id: 'stats-soc',
    groupId: 'soc',
    pageKey: 'soc',
    method: 'GET',
    path: '/api/stats/soc',
    title: 'SOC dashboard stats',
    description: 'Firewall KPIs, denies, top threats — Elasticsearch firewall-* (cached).',
    queryParams: [
      { name: 'range', placeholder: '12h', description: 'ES time range', example: '12h' },
      { name: 'from', placeholder: 'ISO date', description: 'Custom from (with to)' },
      { name: 'to', placeholder: 'ISO date', description: 'Custom to' },
    ],
    responseExample: { denies: 1200, allowed: 50000, topSrcIps: [] },
  }),
  ep({
    id: 'stats-report',
    groupId: 'soc',
    pageKey: 'soc',
    method: 'GET',
    path: '/api/stats/report',
    title: 'SOC/NOC combined report',
    description: 'Combined stats report for dashboards.',
    queryParams: [{ name: 'range', placeholder: '12h', example: '24h' }],
  }),
  ep({
    id: 'logs-search',
    groupId: 'soc',
    pageKey: 'soc',
    method: 'GET',
    path: '/api/logs/search',
    title: 'Search firewall / Cisco logs',
    description: 'Elasticsearch search with query string and time range.',
    queryParams: [
      { name: 'q', placeholder: 'action:deny AND srcip:10.0.0.1', description: 'Lucene query', example: 'action:deny' },
      { name: 'range', placeholder: '24h', example: '24h' },
      { name: 'size', placeholder: '100', example: '50' },
      { name: 'index', placeholder: 'firewall-*', description: 'firewall-* | cisco-*' },
    ],
  }),
  ep({
    id: 'logs-denied',
    groupId: 'soc',
    pageKey: 'soc',
    method: 'GET',
    path: '/api/logs/denied',
    title: 'Denied sessions',
    description: 'Top denied firewall sessions for SOC view.',
    queryParams: [{ name: 'range', placeholder: '1h', example: '1h' }],
  }),
  ep({
    id: 'logs-recent',
    groupId: 'soc',
    pageKey: 'soc',
    method: 'GET',
    path: '/api/logs/events/recent',
    title: 'Recent events',
    description: 'Latest firewall/cisco events stream.',
    queryParams: [{ name: 'limit', placeholder: '50', example: '30' }],
  }),
  ep({
    id: 'logs-export',
    groupId: 'soc',
    pageKey: 'soc',
    method: 'GET',
    path: '/api/logs/export',
    title: 'Export logs (CSV)',
    description: 'Streaming CSV export. Same query params as /search. Long-running — increase timeout.',
    queryParams: [
      { name: 'q', placeholder: 'action:deny', example: 'action:deny' },
      { name: 'range', placeholder: '24h', example: '24h' },
    ],
    notes: ['Response is text/csv stream, not JSON.'],
  }),

  // ── NOC ─────────────────────────────────────────────────────────────────────
  ep({
    id: 'stats-noc',
    groupId: 'noc',
    pageKey: 'noc',
    method: 'GET',
    path: '/api/stats/noc',
    title: 'NOC dashboard stats',
    description: 'Interface / network KPIs from Elasticsearch cisco-* indices.',
    queryParams: [
      { name: 'range', placeholder: '12h', example: '12h' },
      { name: 'from', placeholder: 'ISO' },
      { name: 'to', placeholder: 'ISO' },
    ],
  }),

  // ── Sentinel ES ─────────────────────────────────────────────────────────────
  ep({
    id: 'sentinel-stats',
    groupId: 'sentinel',
    pageKey: 'sentinel',
    method: 'GET',
    path: '/api/sentinel/stats',
    title: 'Sentinel stats',
    description: 'Dashboard KPIs from sentinel-* Elasticsearch index.',
    queryParams: [{ name: 'range', placeholder: '24h', example: '24h' }],
  }),
  ep({
    id: 'sentinel-dashboard',
    groupId: 'sentinel',
    pageKey: 'sentinel',
    method: 'GET',
    path: '/api/sentinel/dashboard',
    title: 'Sentinel dashboard bundle',
    description: 'Aggregated dashboard payload (threats, connectivity, etc.).',
    queryParams: [{ name: 'range', placeholder: '24h', example: '24h' }],
  }),
  ep({
    id: 'sentinel-events',
    groupId: 'sentinel',
    pageKey: 'sentinel',
    method: 'GET',
    path: '/api/sentinel/events',
    title: 'Sentinel events list',
    description: 'Paginated XDR-style events from Elasticsearch.',
    queryParams: [
      { name: 'q', placeholder: 'search text' },
      { name: 'range', placeholder: '24h', example: '24h' },
      { name: 'page', placeholder: '1', example: '1' },
      { name: 'pageSize', placeholder: '50', example: '50' },
    ],
  }),
  ep({
    id: 'sentinel-hostname',
    groupId: 'sentinel',
    pageKey: 'sentinel',
    method: 'GET',
    path: '/api/sentinel/hostname-search',
    title: 'Search by hostname',
    description: 'Find Sentinel events for a store hostname or pattern.',
    queryParams: [
      { name: 'hostname', placeholder: 'RP4531-E521BCXS', description: 'Required', example: 'RP4531' },
      { name: 'range', placeholder: '24h', example: '6h' },
    ],
  }),
  ep({
    id: 'sentinel-usb',
    groupId: 'sentinel',
    pageKey: 'sentinel',
    method: 'GET',
    path: '/api/sentinel/usb-device-search',
    title: 'USB device events',
    description: 'USB connect/disconnect events in time range.',
    queryParams: [
      { name: 'range', placeholder: '1h', example: '1h' },
      { name: 'hostname', placeholder: 'RP4531-E521BCXS' },
    ],
  }),

  // ── SentinelOne API ─────────────────────────────────────────────────────────
  ep({
    id: 's1-configured',
    groupId: 'sentinel-one',
    pageKey: 'sentinel',
    method: 'GET',
    path: '/api/sentinel-one/configured',
    title: 'SentinelOne configured?',
    description: 'Whether SENTINEL_ONE_BASE_URL and API token are set on server.',
    responseExample: { configured: true },
  }),
  ep({
    id: 's1-threats',
    groupId: 'sentinel-one',
    pageKey: 'sentinel',
    method: 'GET',
    path: '/api/sentinel-one/threats',
    title: 'List threats',
    description: 'Management API threats list with filters.',
    queryParams: [
      { name: 'limit', placeholder: '20', example: '10' },
      { name: 'resolved', placeholder: 'false' },
    ],
  }),
  ep({
    id: 's1-xdr-pq',
    groupId: 'sentinel-one',
    pageKey: 'sentinel',
    method: 'POST',
    path: '/api/sentinel-one/xdr/powerQuery',
    title: 'XDR PowerQuery',
    description: 'Run Singularity XDR PowerQuery (Log Read Access token). Used by AI direct-xdr path.',
    sampleBody: {
      query: 'dataset = xdr_data | filter event.type = "Login" | limit 100',
      from: '1h',
    },
    notes: ['Requires SENTINEL_ONE_XDR_BASE_URL + SENTINEL_ONE_XDR_API_TOKEN on server.'],
  }),

  // ── Zabbix ──────────────────────────────────────────────────────────────────
  ep({
    id: 'zabbix-overview',
    groupId: 'zabbix',
    pageKey: 'infra',
    method: 'GET',
    path: '/api/zabbix/overview',
    title: 'Zabbix overview',
    description: 'Host counts by availability, problem summary — infra Zabbix instance.',
    responseExample: { hosts: { total: 500, up: 480, down: 20 }, problems: { high: 3 } },
  }),
  ep({
    id: 'zabbix-hosts',
    groupId: 'zabbix',
    pageKey: 'infra',
    method: 'GET',
    path: '/api/zabbix/hosts',
    title: 'Zabbix hosts',
    description: 'List monitored hosts with status, groups, interfaces.',
    queryParams: [
      { name: 'search', placeholder: 'switch-name', description: 'Name/host search' },
      { name: 'group', placeholder: 'Network', description: 'Host group filter' },
      { name: 'limit', placeholder: '200', example: '100' },
    ],
  }),
  ep({
    id: 'zabbix-problems',
    groupId: 'zabbix',
    pageKey: 'infra',
    method: 'GET',
    path: '/api/zabbix/problems',
    title: 'Zabbix problems',
    description: 'Active problems (triggers) from infra Zabbix.',
    queryParams: [
      { name: 'severity', placeholder: '4', description: 'Min severity 0–5' },
      { name: 'host', placeholder: 'hostname' },
    ],
  }),
  ep({
    id: 'zabbix-host-items',
    groupId: 'zabbix',
    pageKey: 'infra',
    method: 'GET',
    path: '/api/zabbix/hosts/{hostId}/items/latest',
    title: 'Host latest items',
    description: 'Latest values for key items on one host.',
    pathParams: [{ name: 'hostId', placeholder: '12345', description: 'Zabbix hostid' }],
  }),
  ep({
    id: 'store-zabbix-overview',
    groupId: 'store-zabbix',
    pageKey: 'storeZabbix',
    method: 'GET',
    path: '/api/store-zabbix/overview',
    title: 'Store Zabbix overview',
    description: 'Same shape as infra overview but STORE_ZABBIX_* env instance.',
  }),
  ep({
    id: 'store-zabbix-hosts',
    groupId: 'store-zabbix',
    pageKey: 'storeZabbix',
    method: 'GET',
    path: '/api/store-zabbix/hosts',
    title: 'Store Zabbix hosts',
    queryParams: [
      { name: 'search', placeholder: 'RP4531', example: 'RP' },
      { name: 'limit', placeholder: '200', example: '100' },
    ],
  }),

  // ── Admin ─────────────────────────────────────────────────────────────────
  ep({
    id: 'users-list',
    groupId: 'admin',
    pageKey: 'admin',
    method: 'GET',
    path: '/api/users',
    title: 'List users',
    description: 'All portal users with roles, allowedPages, apiAccessEnabled. Admin console.',
    responseExample: [{ email: 'user@example.com', role: 'analyst', apiAccessEnabled: false }],
    notes: ['Typically used from Admin UI; protect network access to /api/users in production.'],
  }),
  ep({
    id: 'users-create',
    groupId: 'admin',
    pageKey: 'admin',
    method: 'POST',
    path: '/api/users',
    title: 'Create user',
    sampleBody: {
      name: 'API User',
      email: 'api@example.com',
      password: 'minimum-8-chars',
      role: 'viewer',
      apiAccessEnabled: true,
      allowedPages: ['storeMonitor', 'ai'],
    },
  }),
  ep({
    id: 'users-update',
    groupId: 'admin',
    pageKey: 'admin',
    method: 'PUT',
    path: '/api/users/{userId}',
    title: 'Update user',
    description: 'Update role, allowedPages, active, apiAccessEnabled. Disabling apiAccess revokes all API tokens.',
    pathParams: [{ name: 'userId', placeholder: 'mongo-object-id' }],
    sampleBody: { apiAccessEnabled: true, allowedPages: ['storeMonitor', 'soc', 'ai'] },
  }),
  ep({
    id: 'devices-list',
    groupId: 'admin',
    pageKey: 'admin',
    method: 'GET',
    path: '/api/devices',
    title: 'List devices',
    description: 'Firewalls, switches — IP, site, mgmt credentials flag.',
  }),
  ep({
    id: 'devices-get',
    groupId: 'admin',
    pageKey: 'admin',
    method: 'GET',
    path: '/api/devices/{deviceId}',
    title: 'Get device',
    pathParams: [{ name: 'deviceId', placeholder: 'mongo-object-id' }],
  }),
  ep({
    id: 'sites-list',
    groupId: 'admin',
    pageKey: 'admin',
    method: 'GET',
    path: '/api/sites',
    title: 'List sites',
    description: 'Sites/locations with IP ranges for device assignment.',
  }),
]

export const API_DOCS_INTRO = {
  title: 'NetPulse REST API reference',
  sections: [
    {
      heading: 'Base URL',
      body: 'Use the same origin as this portal (shown above). All paths are under /api/… except /health. In production, nginx proxies /api to the Node server on port 5000.',
    },
    {
      heading: 'Authentication',
      body: 'Header: Authorization: Bearer <jwt>\n\n• Session JWT — from POST /api/auth/login (browser, ~7 days)\n• API JWT — from POST /api/auth/api-tokens when admin enabled Allow API access (30d–365d, revocable)\n• Agent key — header X-Netpulse-Agent-Key (server env; service user permissions)\n\nYour JWT only accesses pages in allowedPages (same as the portal UI).',
    },
    {
      heading: 'Getting data quickly',
      body: 'For automation, prefer:\n1. GET /api/store-monitor/full — all live store monitor data in one call\n2. POST /api/agent/query — direct answers + full context, no UI\n3. GET /api/store-monitor/overview — stores + summary only (lighter)\n4. POST /api/ai/chat with mode:details — full hostname report\n5. GET /api/logs/search — raw firewall/Cisco logs',
    },
    {
      heading: 'Query parameters',
      body: 'GET endpoints support query strings — use the Query parameters section on each endpoint in this explorer. Values are editable before Send request.',
    },
    {
      heading: 'Rate limits & timeouts',
      body: '500 requests / 15 min per IP on /api/*. Store monitor overview and AI chat can take 30s–6min — use a long client timeout. CSV exports stream; do not expect JSON.',
    },
    {
      heading: 'Page access map',
      body: 'storeMonitor → /api/store-monitor/*, /api/store-alerts/*\nsoc → /api/stats/soc, /api/logs/*\nnoc → /api/stats/noc\nsentinel → /api/sentinel/*, /api/sentinel-one/*\ninfra → /api/zabbix/*\nstoreZabbix → /api/store-zabbix/*\nai → /api/ai/*\nadmin → /api/users, /api/devices, /api/sites (admin page)',
    },
  ],
}
