/**
 * NetPulse REST API catalog for /api-docs explorer.
 * pageKey: omit = any authenticated user; set = requires that portal page.
 */

export const API_DOC_GROUPS = [
  {
    id: 'intro',
    label: 'Getting started',
    intro: true,
  },
  {
    id: 'auth',
    label: 'Authentication',
  },
  {
    id: 'tokens',
    label: 'API tokens',
  },
  {
    id: 'agent',
    label: 'External agent API',
  },
  {
    id: 'ai',
    label: 'AI Assistant',
    pageKey: 'ai',
  },
  {
    id: 'store',
    label: 'Store monitor',
    pageKey: 'storeMonitor',
  },
  {
    id: 'soc',
    label: 'SOC / NOC stats',
    pageKey: 'soc',
  },
  {
    id: 'system',
    label: 'System',
  },
]

export const API_DOC_ENDPOINTS = [
  {
    id: 'health',
    groupId: 'system',
    method: 'GET',
    path: '/health',
    title: 'Health check',
    description: 'No authentication. Returns server status and configured AI provider name.',
    auth: false,
    sampleBody: null,
  },
  {
    id: 'auth-me',
    groupId: 'auth',
    method: 'GET',
    path: '/api/auth/me',
    title: 'Current user profile',
    description: 'Returns your user, role, allowedPages, and pageAccess. Works with portal session JWT or API JWT.',
    auth: true,
    sampleBody: null,
  },
  {
    id: 'auth-login',
    groupId: 'auth',
    method: 'POST',
    path: '/api/auth/login',
    title: 'Login (portal session)',
    description: 'Exchange email + password for a short-lived session JWT. Not for API JWT generation.',
    auth: false,
    sampleBody: { email: 'user@example.com', password: 'your-password' },
  },
  {
    id: 'tokens-list',
    groupId: 'tokens',
    method: 'GET',
    path: '/api/auth/api-tokens',
    title: 'List API tokens',
    description: 'Lists your active API tokens (metadata only). Requires portal login — API JWT cannot call this.',
    auth: true,
    sessionOnly: true,
    sampleBody: null,
  },
  {
    id: 'tokens-create',
    groupId: 'tokens',
    method: 'POST',
    path: '/api/auth/api-tokens',
    title: 'Create API JWT',
    description: 'Creates a long-lived JWT. Response includes token once — copy immediately. Requires apiAccessEnabled on your user.',
    auth: true,
    sessionOnly: true,
    sampleBody: { label: 'automation-script', expiresIn: '90d' },
  },
  {
    id: 'tokens-revoke',
    groupId: 'tokens',
    method: 'DELETE',
    path: '/api/auth/api-tokens/{tokenId}',
    title: 'Revoke API token',
    description: 'Replace {tokenId} with the id from the list endpoint. Portal session required.',
    auth: true,
    sessionOnly: true,
    pathParams: [{ name: 'tokenId', placeholder: 'mongo-object-id' }],
    sampleBody: null,
  },
  {
    id: 'agent-meta',
    groupId: 'agent',
    method: 'GET',
    path: '/api/agent/meta',
    title: 'Agent API metadata',
    description: 'Capabilities, auth method, allowed pages for the authenticated user.',
    auth: true,
    sampleBody: null,
  },
  {
    id: 'agent-modules',
    groupId: 'agent',
    method: 'GET',
    path: '/api/agent/modules',
    title: 'Context modules',
    description: 'Lists portal context modules this user may request in /context or /query.',
    auth: true,
    sampleBody: null,
  },
  {
    id: 'agent-context',
    groupId: 'agent',
    method: 'POST',
    path: '/api/agent/context',
    title: 'Export portal context',
    description: 'JSON (and optional prompt block) for external LLMs — no NetPulse LLM call.',
    auth: true,
    sampleBody: {
      question: 'store monitor summary',
      autoModules: true,
      format: 'both',
    },
  },
  {
    id: 'agent-query',
    groupId: 'agent',
    method: 'POST',
    path: '/api/agent/query',
    title: 'Query with direct answers',
    description: 'Runs fast paths (stores, XDR, Zabbix, SOC) when possible; includes portalContext.',
    auth: true,
    sampleBody: {
      question: 'How many stores are offline?',
      includeContext: true,
    },
  },
  {
    id: 'agent-deliver',
    groupId: 'agent',
    method: 'POST',
    path: '/api/agent/deliver',
    title: 'Query + forward',
    description: 'Same as /query, then POSTs the envelope to your webhook URL(s).',
    auth: true,
    sampleBody: {
      question: 'Sentinel failed login last 1 hour',
      url: 'https://your-agent.example/hooks/netpulse',
      includeContext: true,
    },
  },
  {
    id: 'ai-modules',
    groupId: 'ai',
    pageKey: 'ai',
    method: 'GET',
    path: '/api/ai/modules',
    title: 'AI context modules',
    description: 'Modules available in the AI Assistant for your allowed pages.',
    auth: true,
    sampleBody: null,
  },
  {
    id: 'ai-provider',
    groupId: 'ai',
    pageKey: 'ai',
    method: 'GET',
    path: '/api/ai/provider',
    title: 'AI provider status',
    description: 'Active LLM provider (claude / openai / ollama) and configuration diagnostics.',
    auth: true,
    sampleBody: null,
  },
  {
    id: 'ai-chat',
    groupId: 'ai',
    pageKey: 'ai',
    method: 'POST',
    path: '/api/ai/chat',
    title: 'AI chat',
    description: 'Multi-turn chat with portal context. Many questions use direct (no-LLM) fast paths.',
    auth: true,
    sampleBody: {
      messages: [{ role: 'user', content: 'How many stores are offline?' }],
      autoModules: true,
      mode: 'monitor',
    },
  },
  {
    id: 'store-meta',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/meta',
    title: 'Store monitor meta',
    description: 'Influx configuration and feature flags.',
    auth: true,
    sampleBody: null,
  },
  {
    id: 'store-overview',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/overview',
    title: 'Overview summary',
    description: 'Live counts: total, online, offline, with issues.',
    auth: true,
    sampleBody: null,
  },
  {
    id: 'store-stores',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/stores',
    title: 'Store list',
    description: 'Optional query: status=offline|online|issues, search=hostname fragment.',
    auth: true,
    queryHint: '?status=offline&search=RP',
    sampleBody: null,
  },
  {
    id: 'store-problems',
    groupId: 'store',
    pageKey: 'storeMonitor',
    method: 'GET',
    path: '/api/store-monitor/problems',
    title: 'Active problems',
    description: 'Current problem snapshot from periodic tracker.',
    auth: true,
    sampleBody: null,
  },
  {
    id: 'stats-soc',
    groupId: 'soc',
    pageKey: 'soc',
    method: 'GET',
    path: '/api/stats/soc',
    title: 'SOC dashboard stats',
    description: 'Firewall KPIs from Elasticsearch (last hour window).',
    auth: true,
    sampleBody: null,
  },
  {
    id: 'stats-noc',
    groupId: 'soc',
    pageKey: 'noc',
    method: 'GET',
    path: '/api/stats/noc',
    title: 'NOC dashboard stats',
    description: 'Network / interface KPIs. Requires noc page access.',
    auth: true,
    sampleBody: null,
  },
]

export const API_DOCS_INTRO = {
  title: 'NetPulse REST API',
  sections: [
    {
      heading: 'Base URL',
      body: 'Use the same origin as this portal, or your API host (e.g. https://netpulse.example:5000). The explorer below prefills it automatically.',
    },
    {
      heading: 'Authentication',
      body: 'Send Authorization: Bearer <jwt> on every /api/* request except /health and /api/auth/login. Use a user-generated API JWT (top bar → API → Generate JWT) or your portal session token. Permissions match your allowed portal pages.',
    },
    {
      heading: 'Rate limits',
      body: 'General API routes are limited to 500 requests per 15 minutes per IP. Long-running exports and AI chat may take longer — increase client timeout for those paths.',
    },
    {
      heading: 'External agents',
      body: 'Alternatively, server admins can configure NETPULSE_AGENT_API_KEY plus a service user. See docs/EXTERNAL-AGENT-API.md in the repository for agent key auth and webhooks.',
    },
  ],
}
